### ISSUE TITLE
add pipx to install options

### ISSUE THREAD

**Issue by zachvalenta** [saulpw/visidata.org#19]
pipx is a tool to manage Python dependencies that you want to have globally available. To give a sense of the type of deps you might use pipx for:

```sh
$ pipx list
venvs are in /Users/zach/.local/pipx/venvs
apps are exposed on your $PATH at /Users/zach/.local/bin

   package ansible 2.8.6, Python 3.6.1
    - ansible
    - ansible-config
   package poetry 1.0.0, Python 3.6.1
    - poetry
   package visidata 1.5.2, Python 3.6.1
    - vd
``` 

Seems like a perfect fit for vd.

**Comment by anjakefala** [comment]
Hi @zachvalenta, is there any difference in the instructions between `pip3` and `pipx`? 

You are definitely not the only advocate for `pipx`. =) @ajkerrigan has made changes to VisiData core to accomodate it: https://github.com/saulpw/visidata/pull/355. 

I agree about adding at least a note in the `pip3` section about its existence as an option. ^^

**Comment by anjakefala** [comment]
Would actually @zachvalenta or @ajkerrigan mind attempting to add pipx documentation into https://github.com/saulpw/visidata.org/blob/master/install.md?

**Comment by ajkerrigan** [comment]
Sure thing @anjakefala, I don't mind adding a mention about pipx (if you'd rather run with it that's cool too @zachvalenta). Glancing at the pip3 section in that file raises another question for pip/pipx installs though: would it be valuable to have an optional/[extras](https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies) install target like "all" or "full" that could optionally install all loaders?

So maybe `pip install visidata` would give you the base set of loaders, but `pip install visidata[full]` would install all dependencies without having to download requirements.txt separately?

**Comment by saulpw** [comment]
@ajkerrigan With the plugins system in place, I've actually been thinking we should pluginify the loaders with external dependencies.  Probably batching some common ones together, like the loaders that depend on pandas.  Then the core VisiData install can be short and sweet, and we can focus our energy on which Python package manager to use to install the dependencies themselves.  Is this a terrible idea?

**Comment by ajkerrigan** [comment]
That seems like a fine idea @saulpw. Goes well with the stubbing idea you mentioned in saulpw/visidata#449.

I was thinking of `pip install visidata[full]` purely as an alternative to this piece of the readme:

> To install dependencies for all loaders (which might take some time and disk space):
>
> ```
> wget https://raw.githubusercontent.com/saulpw/visidata/stable/requirements.txt
> pip3 install -r requirements.txt
> ```

Would that sort of optional "batteries included" guidance go away if loaders with external dependencies get pluginified?

**Comment by saulpw** [comment]
Yes, I think this would either go away completely, or be replaced with a blurb that shows how people can select all loaders in the plugins sheet and install them en masse.  (This would mean the plugins sheet would have to indicate loaders specifically; either with a tag or by ensuring the description for each loader plugin has "loader" in it specifically.)

**Comment by anjakefala** [comment]
Wholehearted thanks to @ajkerrigan for handling this. :tada:
