### ISSUE TITLE
broken link on https://www.visidata.org/docs/loading/

### ISSUE THREAD

**Issue by shapr** [saulpw/visidata.org#43]
The page https://www.visidata.org/docs/loading/ has text "loaders" that links to https://www.visidata.org/docs/loaders , perhaps it should link to https://www.visidata.org/docs/api/loaders instead?

**Comment by saulpw** [comment]
@zachvalenta got to it first :)  https://github.com/saulpw/visidata/commit/96487a9fd77cf2b84d29854ff45179433614de00
