### ISSUE TITLE
motd.visidata.org: Expired TLS certificate

### ISSUE THREAD

**Issue by koernepr** [saulpw/visidata.org#47]
The TLS certificate of `motd.visidata.org` expired:

    Validity
        Not Before: Apr  4 23:13:19 2021 GMT
        Not After : Jul  3 23:13:19 2021 GMT

**Comment by anjakefala** [comment]
@koernepr Thanks so much for letting us know!

**Comment by anjakefala** [comment]
Hi @koernepr, we are grateful to you for letting us know about this. If you drop by `#visidata` on https://libera.chat/, we would love to coordinate with you to send you some VisiData stickers.

Drop on by, if you would like this!
